name: app
description: "大蓝典 - 企业级 Flutter 应用"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Router
  go_router: ^17.3.0

  # State Management
  flutter_riverpod: ^3.4.2

  # Immutable Model
  freezed_annotation: ^3.1.0

  # Json
  json_annotation: ^4.9.0

  # Utils
  intl: ^0.20.3
  uuid: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  build_runner: ^2.15.1
  freezed: ^3.2.5
  json_serializable: ^6.11.2

flutter:
  uses-material-design: true